#! /usr/bin/octave

list={
CH3             
ClO             
HCO             
NH2             
NH              
NO2             
NO              
O2              
OH              
S2              
SiH3            
H2              
Cl2             
ClF             
CO              
CS              
F2              
HCl             
HF              
N2              
P2              
SiO          
NaCl            
CO2             
H2O             
H2S             
HCN             
SO2             
CS2             
SiF2            
F2O             
NNO             
NSF             
O3              
OCS             
FCN             
HOCl         
CH2O            
H2O2            
NH3             
PH3             
C2N2            
HCCF         
AlCl3           
BCl3            
BF3               
CF2O              
ClF3              
H2CS              
NF3               
PF3               
C2H2              
C3O2           
CBrF3             
CCl2F2            
CCl3H             
CCl4              
CClF3             
CF4            
CFCl3             
CH2Cl2            
CH2CO             
CH2F2          
CH3Cl             
CH3F           
CH4            
CHF3              
HCCCN         
HCOOH             
NSF3              
SiF4              
SiH4          
C2F4              
C2H4              
CF3CN             
CH2CF2            
CH3CN             
CH3NC             
CH3OH             
CH3SH             
CHFCF2         
Z-CHF-CHF    
Cl2CCF2           
Chloroethene      
Fluoroethene      
H2CCCl2           
HCCCCH         
HCCCHO            
HCONH2            
N2H4              
NCCCCN        
OCHCHO            
Acrylonitrile     
CH2CCH2           
CH3CCH            
CH3CClO           
CH3NO2            
Cyclopropene      
Ethylene_oxide    
Thiirane          
HCCCCCN       
SF6               
Acrolein      
CH3CCCN       
CH3CH2Cl          
CH3CH3        
CH3SiH3           
CH4N2O                 
Ethylenimine           
1_1-Dicyanoethylene    
Si2H6                  
s-Tetrazine        
2-Propenoic_acid       
CH3CH2OH               
CH3CONH2               
CH3OCH3                
Cyclopropane       
Furan              
Propene                
Thiophene              
1_3-Butadiene          
2-Propen-1-ol          
2-Propenamide          
CH3CCCH3               
CH3COCH3               
CH3NHCH3               
CH3SOCH3               
Cyclobutene            
Pyrrole                
Methoxyethene          
Methylacrylonitrile    
Pyrazine               
Pyrimidine             
Pyridine               
1-Chloropropane        
Butenone               
CH3CH2CH3      
Fulvene            
Vinyl_acetate          
Methyl_prop-2-enoate   
Isoprene               
NC3H9                  
2-Methylpropene        
Isobutane          
2-Vinylpyridine        
Styrene                
Benzene            
Naphthalene     
