#! /usr/bin/octave-cli -q

list={...
       "acetaldehyde","acetic","al","alcl","alcl3","alf","alf3","alh",...
       "alh3","allene","b","b2","b2h6","be","be2","becl2",...
       "bef2","bf","bf3","bh","bh3","bhf2","bn","bn3pi",...
       "c","c2","c2h2","c2h3f","c2h4","c2h5f","c2h6","cch",...
       "ccl2","cf","cf2","cf4","ch","ch2c","ch2ch","ch2f2",...
       "ch2nh","ch2nh2","ch2-sing","ch2-trip","ch3","ch3f","ch3nh","ch3nh2",...
       "ch4","c-hcoh","c-hono","c-hooo","cl","cl2","cl2o","clcn",...
       "clf","clo","cloo","cn","c-n2h2","co","co2","cs",...
       "cs2","dioxirane","ethanol","f","f2","f2co","f2o","fccf",...
       "fo2","foof","formic","glyoxal","h","h2","h2cn","h2co",...
       "h2o","h2s","hccf","hcl","hcn","hcnh","hcno","hco",...
       "hcof","hf","hnc","hnco","hnnn","hno","hocl","hocn",...
       "hof","honc","hoo","hooh","hs","ketene","methanol","n",...
       "n2","n2h","n2h4","n2o","nccn","nh","nh2","nh2cl",...
       "nh3","no","no2","o","o2","o3","oclo","ocs",...
       "of","oh","oxirane","oxirene","p","p2","p4","ph3",...
       "propane","propene","propyne","s","s2","s2o","s3","s4-c2v",...
       "si","si2h6","sif","sif4","sih","sih3f","sih4","sio",...
       "so","so2","so3","ssh","t-hcoh","t-hono","t-hooo","t-n2h2"};

for i = 1:length(list)
  [s out] = system(sprintf("cat %s/.CHRG",list{i}));
  q = str2num(out);
  [s out] = system(sprintf("cat %s/.UHF",list{i}));
  mm = str2num(out) + 1;
  mol = mol_readxyz(sprintf("%s/struc.xyz",list{i}));

  fid = fopen(sprintf("%s.xyz",list{i}),"w");
  fprintf(fid,"%d\n",mol.nat);
  fprintf(fid,"%d %d\n",q,mm);
  for j = 1:mol.nat
    fprintf(fid,"%s %.10f %.10f %.10f\n",mol.atname{j},mol.atxyz(:,j));
  endfor
  fclose(fid);

  fid = fopen(sprintf("%s.gjf",list{i}),"w");
  fprintf(fid,"%%nprocs=4\n");
  fprintf(fid,"%%mem=2GB\n");
  fprintf(fid,"#p pbepbe aug-cc-pvtz output=wfx scf=(conver=6) int=(grid=ultrafine)\n");
  fprintf(fid,"\n");
  fprintf(fid,"title\n");
  fprintf(fid,"\n");
  fprintf(fid,"%d %d\n",q,mm);
  for j = 1:mol.nat
    fprintf(fid,"%s %.10f %.10f %.10f\n",mol.atname{j},mol.atxyz(:,j));
  endfor
  fprintf(fid,"\n");
  fprintf(fid,"%s.wfx\n",list{i});
  fprintf(fid,"\n");
  fclose(fid);
endfor

