#! /usr/bin/octave-cli -q

# Copyright (c) 2016 Alberto Otero de la Roza <alberto@fluor.quimica.uniovi.es>
#
# refdata is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

din={...
      "../10_din/gmtkn30_aconf.din",...
      "../10_din/gmtkn30_adim6.din",...
      "../10_din/gmtkn30_bhperi.din",...
      "../10_din/gmtkn30_bsr36.din",...
      "../10_din/gmtkn30_darc.din",...
      "../10_din/gmtkn30_idisp.din",...
      "../10_din/gmtkn30_iso34.din",...
      "../10_din/gmtkn30_isol22.din",...
      "../10_din/gmtkn30_pconf.din",...
      "../10_din/gmtkn30_sconf.din",...
      "../10_din/s30l.din",...
    };
names={...
      "gmtkn30_aconf",...
      "gmtkn30_adim6",...
      "gmtkn30_bhperi",...
      "gmtkn30_bsr36",...
      "gmtkn30_darc",...
      "gmtkn30_idisp",...
      "gmtkn30_iso34",...
      "gmtkn30_isol22",...
      "gmtkn30_pconf",...
      "gmtkn30_sconf",...
      "s30l",...
      };
dirs={...
       "../20_gmtkn30_aconf/",...
       "../20_gmtkn30_adim6/",...
       "../20_gmtkn30_bhperi/",...
       "../20_gmtkn30_bsr36/",...
       "../20_gmtkn30_darc/",...
       "../20_gmtkn30_idisp/",...
       "../20_gmtkn30_iso34/",...
       "../20_gmtkn30_isol22/",...
       "../20_gmtkn30_pconf/",...
       "../20_gmtkn30_sconf/",...
       "../20_s30l/",...
     };

## globals
format long;
hy2kcal=627.51;

source("load_din.m");

for idin = 1:length(din)
  [n rxn] = load_din(din{idin});

  ## write the db files
  for i = 1:n
    name = sprintf("%s_%3.3d",names{idin},i);
    fid = fopen(sprintf("%s.db",name),"w");
    fprintf(fid,"type reaction_frozen");
    fprintf(fid,"ref %.4f\n",rxn{i}{end});
    for j = 1:(length(rxn{i})-1)/2
      mol = mol_readxyz(sprintf("%s/%s.xyz",dirs{idin},rxn{i}{2*j}));
      [q m] = sscanf(mol.name,"%d %d","C");
      fprintf(fid,"molc %.1f %d %d\n",rxn{i}{2*j-1},q,m);
      for k = 1:mol.nat
        fprintf(fid,"%s %.10f %.10f %.10f\n",mol.atname{k},mol.atxyz(:,k));
      endfor
      fprintf(fid,"end\n");
    endfor
    fclose(fid);
  endfor
endfor
